### ISSUE TITLE
Open Hihat continues to play until a closed hihat event

### ISSUE THREAD

**Issue by isatellite** [joebritt/luma1#1]
When pressing the open hihat button the sound continues to play. This issue is also happening when using either the front panel button or over MIDI to trigger the open hihat. If you stop a sequencer while the open hihat is playing, it will remain playing after the sequence is stopped. If you hit the closed hihat button, it will stop.

This is not the way it works on the original LM-1. It is a looped sample but it is gated on the original machine.

**Comment by joebritt** [comment]
Luma-1 V2 board v1.2: change R15 from 8k2 to 18k0 5% to make Open HiHat reliably close
